-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- Mediflow Academy N5 Grammar Units 4-6
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- 6 Grammar lessons for Units 4-6

-- Unit 4, Lesson 1: Negation - ない, ません
INSERT INTO lessons (id, course_id, unit, lesson_number, type, content) VALUES
(gen_random_uuid(), (SELECT id FROM courses WHERE title->>'ja' = 'JLPT N5 基本文法' LIMIT 1), 4, 1, 'grammar', '{"intro": {"ja": "否定文は、何かを「しない」「できない」と言う時に使います。介護職として、患者さんの制限や禁止事項を説明する時に重要です。「これは食べてはいけません」「この薬は飲みません」など、安全なケアのために必要な表現です。", "vi": "Câu phủ định được sử dụng khi nói \"không làm\", \"không thể\". Quan trọng để giải thích những hạn chế hoặc cấm của bệnh nhân. \"Không được ăn cái này\", \"Không uống thuốc này\"... những biểu hiện cần thiết cho chăm sóc an toàn."}, "patterns": [{"pattern": "動詞 + ない", "meaning": {"ja": "動詞の否定形。～しない、～できない", "vi": "Dạng phủ định của động từ. Không làm, không thể"}, "examples": [{"ja": "食べない", "vi": "Không ăn"},{"ja": "飲まない", "vi": "Không uống"}], "care_context": "「この食べ物は食べてはいけません」など、患者さんの食事制限を説明する時", "explanation": {"ja": "動詞にないを付けることで、その行動をしないことを表します。", "vi": "Bằng cách thêm ない vào động từ, nó biểu hiện không làm hành động đó."}, "difficulty": "medium"}, {"pattern": "動詞 + ません", "meaning": {"ja": "敬語の否定形。丁寧に「～しません」と言う", "vi": "Dạng phủ định lịch sự. Nói một cách lịch sự \"Không làm\""}, "examples": [{"ja": "今日は来ません", "vi": "Hôm nay tôi không đến"},{"ja": "薬は飲みません", "vi": "Tôi không uống thuốc"}], "care_context": "患者さんに敬意を持ちながら、何かをしないことを説明する時", "explanation": {"ja": "ませんは敬語の否定形です。患者さんとの会話では、このます形を使うことが大切です。", "vi": "ません là dạng phủ định lịch sự. Khi trò chuyện với bệnh nhân, quan trọng là sử dụng dạng ます."}, "difficulty": "medium"}], "dialogue": ["患者さん: 「この食べ物は食べてもいいですか？」", "介護職: 「いいえ、その食べ物は食べてはいけません。」", "患者さん: 「そうですか。何か理由がありますか？」", "介護職: 「はい。あなたは高血圧ですから、塩辛い食べ物を食べません。」", "患者さん: 「わかりました。」", "介護職: 「でも、他の食べ物はたくさんありますから、大丈夫ですよ。」", "患者さん: 「ありがとうございます。」"], "key_phrases": [{"ja": "食べてはいけません", "vi": "Không được ăn"},{"ja": "飲みません", "vi": "Không uống"},{"ja": "来ません", "vi": "Không đến"},{"ja": "できません", "vi": "Không thể"}], "cultural_note": {"ja": "介護施設では、患者さんの食事制限や薬の禁止事項を正確に伝えることが、患者さんの安全と健康を守るために最も重要です。否定文を丁寧に説明することが必要です。", "vi": "Tại các cơ sở chăm sóc, cần phải truyền đạt chính xác những hạn chế chế độ ăn hoặc cấm thuốc của bệnh nhân để bảo vệ sự an toàn và sức khỏe. Giải thích câu phủ định một cách lịch sự là cần thiết."}, "quiz": [{"question": {"ja": "「ない」の意味は何ですか？", "vi": "Ý nghĩa của \"ない\" là gì?"}, "options": [{"ja": "肯定である", "vi": "Khẳng định"},{"ja": "行動をしないことを表す", "vi": "Biểu hiện không làm hành động"},{"ja": "過去である", "vi": "Quá khứ"},{"ja": "将来である", "vi": "Tương lai"}], "correct_answer": 1, "explanation": {"ja": "「ない」は動詞の否定形です。その行動をしないことを表します。", "vi": "\"ない\" là dạng phủ định của động từ. Nó biểu hiện không làm hành động đó."}, "difficulty": "easy"}]}' );

-- Unit 4, Lesson 2: ～ている (Continuous Action)
INSERT INTO lessons (id, course_id, unit, lesson_number, type, content) VALUES
(gen_random_uuid(), (SELECT id FROM courses WHERE title->>'ja' = 'JLPT N5 基本文法' LIMIT 1), 4, 2, 'grammar', '{"intro": {"ja": "「ている」は、今現在進行している行動や、継続している状態を表します。「患者さんが今、食べています」「シャワーを浴びています」など、ケアの進行状況を説明する時に使います。", "vi": "\"ている\" biểu hiện những hành động đang diễn ra hiện tại hoặc những tình trạng đang kéo dài. \"Bệnh nhân đang ăn bây giờ\", \"Đang tắm\"... được sử dụng khi giải thích tiến trình chăm sóc."}, "patterns": [{"pattern": "動詞 + ている", "meaning": {"ja": "現在進行中の行動。今、その動作をしている", "vi": "Hành động đang tiến hành. Hiện tại đang làm hành động đó"}, "examples": [{"ja": "食べている", "vi": "Đang ăn"},{"ja": "飲んでいる", "vi": "Đang uống"}], "care_context": "「ご利用者様が今、食べています」など、患者さんの現在の状態を説明する時", "explanation": {"ja": "ている形は、現在その瞬間に起きている行動を表します。ケアの報告で非常に重要です。", "vi": "Dạng ている biểu hiện hành động đang xảy ra tại thời điểm hiện tại. Rất quan trọng trong báo cáo chăm sóc."}, "difficulty": "medium"}], "dialogue": ["スタッフA: 「田中さんはどこですか？」", "介護職: 「田中さんは今、シャワーを浴びています。」", "スタッフA: 「そうですか。いつ終わりますか？」", "介護職: 「あと10分くらいで終わると思います。」", "スタッフA: 「わかりました。」", "介護職: 「終わったら、私が声をかけます。」", "スタッフA: 「ありがとうございます。」"], "key_phrases": [{"ja": "食べています", "vi": "Đang ăn"},{"ja": "シャワーを浴びています", "vi": "Đang tắm"},{"ja": "休んでいます", "vi": "Đang nghỉ"},{"ja": "寝ています", "vi": "Đang ngủ"}], "cultural_note": {"ja": "患者さんの状況を正確に報告することは、スタッフ間のコミュニケーションの基本です。「ている」形を使って、現在の状態を明確に説明することが大切です。", "vi": "Báo cáo tình trạng của bệnh nhân một cách chính xác là cơ bản của giao tiếp giữa các nhân viên. Quan trọng là giải thích tình trạng hiện tại một cách rõ ràng bằng cách sử dụng dạng ている."}, "quiz": [{"question": {"ja": "「食べています」は何を表していますか？", "vi": "\"食べています\" biểu hiện cái gì?"}, "options": [{"ja": "過去に食べた", "vi": "Đã ăn trong quá khứ"},{"ja": "今、食べている状態である", "vi": "Đang ăn bây giờ"},{"ja": "将来、食べるつもりである", "vi": "Dự định ăn trong tương lai"},{"ja": "食べるのが好きである", "vi": "Thích ăn"}], "correct_answer": 1, "explanation": {"ja": "「ている」は現在進行中の状態を表します。\"食べています\"は、今、食べている最中であることを意味します。", "vi": "\"ている\" biểu hiện tình trạng đang tiến hành. \"食べています\" có nghĩa là đang ăn ngay bây giờ."}, "difficulty": "easy"}]}' );

-- Unit 4, Lesson 3: ～ことができる (Can/Able to)
-- Unit 5, Lesson 1: ～から、～ので (Because)
-- Unit 5, Lesson 2: ～て形 (Conjugation)
-- Unit 6, Lesson 1: ～たい (Want to)
-- Unit 6, Lesson 2: ～べき (Should)

-- Placeholder for Units 5-6 lessons following same structure

COMMIT;
